CREATE DATABASE QLCHDT
GO
USE QLCHDT
GO

CREATE TABLE TAIKHOAN(
  MATAIKHOAN INT IDENTITY PRIMARY KEY,
  USERNAME NVARCHAR(30),
  PASS NVARCHAR(30),
  DISLAY_NAME NVARCHAR(30), -- TEN HIEN THI
  NGAY_LAP DATE DEFAULT(GETDATE()),
  LOAI_TAI_KHOAN NVARCHAR(30), -- GAN GIONG VOI LOAI NHAN VIEN, LOAI TAI KHOAN BAO GOM: NHAN VIEN MUA BAN, NHAN VIEN SUA CHUA, ADMIN, KHACH HANG   
  AVATAR NVARCHAR(100) DEFAULT(N'Img/TaiKhoan/Default.jpg')
)
CREATE TABLE QUYEN_CHA(
  MAQUYEN INT IDENTITY PRIMARY KEY,
  TENQUYEN NVARCHAR(30) ,
)

CREATE TABLE QUYEN_CON(
  MAQUYEN INT IDENTITY PRIMARY KEY,
  MAQUYEN_CHA INT FOREIGN KEY (MAQUYEN_CHA)REFERENCES QUYEN_CHA (MAQUYEN) ON  DELETE CASCADE  ON UPDATE CASCADE, 
  TENQUYEN NVARCHAR(30)
)
CREATE TABLE HOPTHU_DEN(
  NG_GUI  INT  FOREIGN KEY (NG_GUI) REFERENCES TAIKHOAN( MATAIKHOAN) ON DELETE CASCADE ON UPDATE CASCADE, 
  NG_NHAN INT  FOREIGN KEY (NG_NHAN) REFERENCES TAIKHOAN( MATAIKHOAN), 
  NGAYGUI DATETIME DEFAULT(GETDATE()),
  DAXEM BIT,
  NOIDUNG NVARCHAR,

  CONSTRAINT PK_THUNHAN PRIMARY KEY(NG_GUI,NG_NHAN,NGAYGUI)
)
-- TIN NHAN LA THU GIUA CAC TAI KHOAN VOI NHAU, THONG BAO LA TIN TU ADMIN DEN MOI TAI KHOAN
CREATE TABLE THONGBAO(
  MA_THONGBAO INT PRIMARY KEY IDENTITY,
  THONGBAO_NAYLA_CU BIT,
  NOIDUNG NVARCHAR,
)


CREATE TABLE NHOMQUYEN_COBAN(
  LOAI_TK NVARCHAR(30) NOT NULL , 
  MAQUYEN_CON INT FOREIGN KEY (MAQUYEN_CON) REFERENCES QUYEN_CON(MAQUYEN) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT PK_NHOMQUYEN PRIMARY KEY(LOAI_TK,MAQUYEN_CON)
)
CREATE TABLE HANGSX(
  MAHSX INT IDENTITY PRIMARY KEY,
  TENHANG NVARCHAR(30),
  QUOCGIA NVARCHAR(30)
)
-- CHITIETSANPHAM PHAI DUOC VIET THEO DANG <TEN THUOC TINH 1>:<GIA TRI>;<TEN THUOC TINH 2>:<GIA TRI>;.......
-- VD RAM:4GB;ROM:32GB;MANG HINH:5,6ICNH;CAMERA TRUOC:14MPX;CAMERA SAU:14MPX
-- LUU Y : KHONG DUNG KHOANG CAC O TRUOC VA SAU DAU ':' ,CUNG NHU TRUOC VA SAU DAU ';'
CREATE TABLE SANPHAM(
  MASP INT IDENTITY PRIMARY KEY,
  TENSP NVARCHAR(60),
  SOLUONGTONKHO INT DEFAULT (0),
  GIA INT ,
  GIABAN INT,
  LOAI NVARCHAR(15) CHECK (LOAI IN ('DIEN THOAI','LINH KIEN')),
  DUONGDAN_HINHANH NVARCHAR(200),
  CHITIET NVARCHAR(500),
  MAHSX INT FOREIGN KEY (MAHSX) REFERENCES HANGSX( MAHSX),
 
)
CREATE TABLE DANHGIA(
  MASP INT PRIMARY KEY,
  TOTAL_SCORE INT DEFAULT(0) , 
  ONE_STAR INT DEFAULT(0) ,
  TOW_STAR INT DEFAULT(0) ,
  THREE_STAR INT DEFAULT(0) ,
  FOUR_STAR INT DEFAULT(0) ,
  FIVE_STAR INT DEFAULT(0) ,
)

CREATE TABLE NHANVIEN(
  MANV INT IDENTITY PRIMARY KEY,
  TENNV NVARCHAR(30),
  CMND NVARCHAR(12),
  QUEQUAN NVARCHAR(30),
  NAMSINH DATE DEFAULT(GETDATE()),
  DIACHITHUONGTRU NVARCHAR(30),
  SDT NVARCHAR (10),
  LUONG INT ,
  NGAYVAOLAM DATE DEFAULT(GETDATE()),
  GIOITINH BIT,
  ANHCHANDUNG NVARCHAR(40),
  CHUCVU NVARCHAR(30) CHECK (CHUCVU IN ('CHU SHOP','QUAN LY','NHAN VIEN MUA BAN','NHAN VIEN SUA CHUA')),
  MATK INT FOREIGN KEY  (MATK) REFERENCES TAIKHOAN(MATAIKHOAN)

)


CREATE TABLE KHACHHANG(
  MAKH INT IDENTITY PRIMARY KEY,
  TENKH NVARCHAR(30),
  SDT NVARCHAR(10)  ,
  DIACHI NVARCHAR(50),
)

CREATE TABLE HOADON(
  MAHD INT IDENTITY PRIMARY KEY,
  MAKH INT FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE ON UPDATE CASCADE,
  MANV INT FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE ON UPDATE CASCADE,
  NGAYLAP DATE DEFAULT(GETDATE()),
  TONGTIEN INT ,
)

---LICH SU SAN PHAM DA XEM CUA KHACH HANG , TOI DA LUU GIU DUOC 12 SAN PHAM DA XEM
CREATE TABLE LICHSUXEM(
    MATAIKHOAN INT FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN) ON  DELETE CASCADE  ON UPDATE CASCADE,
    MA_SANPHAM INT FOREIGN KEY (MA_SANPHAM) REFERENCES SANPHAM(MASP), 
	NGAYXEM DATE DEFAULT(GETDATE()),
	CONSTRAINT PK_LICHSUXEM PRIMARY KEY(MATAIKHOAN,MA_SANPHAM,NGAYXEM)
)
---LICH SU DA SAN PHAM DA MUA CUA KHACH HANG , TOI DA LUU GIU DUOC 12 SAN PHAM DA XEM
CREATE TABLE LICHSUMUA(
    MATAIKHOAN INT FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN) ON  DELETE CASCADE  ON UPDATE CASCADE,
    MA_SANPHAM INT FOREIGN KEY (MA_SANPHAM) REFERENCES SANPHAM(MASP), 
	NGAYMUA DATE DEFAULT(GETDATE()),
	SOLUONG INT,
    THANHTOAN_XONG BIT,
	THANHTIEN INT,
	CONSTRAINT PK_LICHSUMUA PRIMARY KEY(MATAIKHOAN,MA_SANPHAM,NGAYMUA)
)
CREATE TABLE GIOHANG(
    MATAIKHOAN INT FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN) ON  DELETE CASCADE  ON UPDATE CASCADE,
    MA_SANPHAM INT FOREIGN KEY (MA_SANPHAM) REFERENCES SANPHAM(MASP), 
    SOLUONG INT,
    DAMUA BIT DEFAULT (0),
    NGAYMUA DATE DEFAULT(GETDATE()),
   CONSTRAINT PK_GIOHANG PRIMARY KEY(MATAIKHOAN,MA_SANPHAM,NGAYMUA)
)
-- TAI KHOAN LOAI KHACH HANG DUNG DE LUU GIU CAC THONG TIN KHAC CUA KHACH HANG (CON LAI DEU GIONG VOI TAI KHOAN QUAN LY)
CREATE TABLE TAIKHOAN_KHACH(
  MATAIKHOAN INT FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOAN(MATAIKHOAN) ON  DELETE CASCADE  ON UPDATE CASCADE,
  LOAI_KHACH NVARCHAR(30) CHECK(LOAI_KHACH IN ('VIP','THUONG','VANG LAI')), -- LOAI KHACH : KHACH MUA SO LUONG SAN PHAM > 50 LA VIP , <50 VA > 20 LA THUONG, < 20 LA VANG LAI, TU DO TA CO CAC CHINH SACH KHUYEN MAI RIENG
  MAKH  INT FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON  DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT PK_TAIKHOANG_KHACH PRIMARY KEY(MATAIKHOAN) 

) 

CREATE TABLE NHANXET_SP (
  MASP INT FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP) ON DELETE CASCADE ON UPDATE CASCADE,
  MATAIKHOAN INT  FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOAN( MATAIKHOAN) ON DELETE CASCADE ON UPDATE CASCADE, 
  NOIDUNG NTEXT,
  TITILE NVARCHAR(200),
  LIKE_ INT DEFAULT(0),
  DISLIKE INT DEFAULT(0),
  SCORE INT DEFAULT(0),
  POSTTIME DATETIME DEFAULT(GETDATE()),
  CONSTRAINT PK_NHANXET_SP PRIMARY KEY(MASP, MATAIKHOAN)
)

CREATE TABLE CHITIET_HOADON(
  MAHD INT FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD), 
  MASP INT FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP),
  SOLUONG INT,
  CONSTRAINT PK_CT PRIMARY KEY(MAHD, MASP)
)

CREATE TABLE KHUYENMAI(
  MAKM INT IDENTITY PRIMARY KEY,
  LOAI NVARCHAR(17) CHECK (LOAI IN ('GIAM GIA', 'SALE KHUNG'))
)
CREATE TABLE KHUYENMAI_GIAMGIA(
  MAKM INT FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM) ON DELETE CASCADE,
  MASP INT FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) ON DELETE CASCADE, 
  PHANTRAM INT ,
  CONSTRAINT PK_TANGQUA PRIMARY KEY (MAKM)
)

CREATE TABLE KHUYENMAI_SALEKHUNG(
   MAKM INT FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM) ON DELETE CASCADE,
   PHANTRAM INT ,
  CONSTRAINT PK_KHUYENMAI_SALEKHUNG PRIMARY KEY  (MAKM)
)

CREATE TABLE CHINHSACH_KHUYENMAI(
   MAKM INT FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM) ON DELETE CASCADE,
   NGAYBD DATE DEFAULT (GETDATE()),
   NGAYKT DATE DEFAULT (GETDATE()),
   CONSTRAINT PK_CSKM PRIMARY KEY(MAKM, NGAYBD, NGAYKT)
)


-----------------------------------------------------------------------
-----------------------------TRIGGER --------------------------------
----------------------------------------------------------------------
GO
CREATE TRIGGER TRIGGER_SANPHAM_INSERTED 
ON SANPHAM
FOR INSERT
AS BEGIN
   DECLARE @GIA INT, @MA INT;
   SELECT @GIA = GIA, @MA = MASP FROM inserted
   
   UPDATE SANPHAM SET GIABAN = @GIA WHERE MASP = @MA  
END
GO
-------------------------------------------------------------------------------------------------------
-------------------------------------------NHAP DU LIEU------------------------------------------------
-------------------------------------------------------------------------------------------------------
----QUYEN CHA---

INSERT INTO QUYEN_CHA VALUES ('QUAN LY KHO')  -- DAY LA QUYEN CO BAN NHAT
INSERT INTO QUYEN_CHA VALUES('MUA SAN PHAM')  -- QUYEN CUA KHACH HANG
INSERT INTO QUYEN_CHA VALUES('CHINH SACH KHUYEN MAI') -- QUYEN ADMIN
INSERT INTO QUYEN_CHA VALUES('QUAN LY NHAN SU')  -- QUYEN  ADMIN
INSERT INTO QUYEN_CHA VALUES('SUA CHUA SAN PHAM') -- QUYEN NHAN VIEN KI THUAT
INSERT INTO QUYEN_CHA VALUES('BAO CAO KINH DOANH') --ADMIN 
INSERT INTO QUYEN_CHA VALUES('QUAN LY HOA DON')   -- QUYEN NHAN VIEN MUA BAN
INSERT INTO QUYEN_CHA VALUES('QUAN LY TAI KHOAN') -- DAY LA QUYEN CO BAN NHAT

-- QUYEN CON THEO QUYEN CUA CHA--
--INSERT INTO QUYEN_CON(MAQUYEN_CHA,TENQUYEN) VALUES(1,'XEM')
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(1,'QLCB KHO') -- THEM XOA SUA XUAT FILE 1
INSERT INTO QUYEN_CON(MAQUYEN_CHA,TENQUYEN) VALUES(1,'NHAP HANG') --2

INSERT INTO QUYEN_CON(MAQUYEN_CHA,TENQUYEN) VALUES(2,'THANH TOAN ONLINE') --3
INSERT INTO QUYEN_CON(MAQUYEN_CHA,TENQUYEN) VALUES(2,'GIO HANG')--4
INSERT INTO QUYEN_CON(MAQUYEN_CHA,TENQUYEN) VALUES(2,'DAT HANG')--5
INSERT INTO QUYEN_CON(MAQUYEN_CHA,TENQUYEN) VALUES(2,'TRA GOP')--6

INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(3,'QLCB CSKM') -- THEM XOA SUA XUAT FILE 7

INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(4,'QLCB NHAN SU') -- THEM XOA SUA XUAT FILE 8

INSERT INTO QUYEN_CON(MAQUYEN_CHA ,TENQUYEN) VALUES(5,'QLCB SUA CHUA') --9

INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(6,'KINH DOANH') --10
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(6,'THONG TIN MUA BAN')--11
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(6,'XUAT HOA DON')--12

INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(7,'QLCB HOA DON') -- THEM XOA SUA XUAT FILE 13
 
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(8,'THEM TK') -- 14
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(8,'CAP NHAT TK')--15
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(8,'DOI MAT KHAU')--16
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(8,'KIEM TRA LOAI TK')--17
INSERT INTO QUYEN_CON(MAQUYEN_CHA, TENQUYEN) VALUES(8,'THEM QUYEN')--18

------------ TAI KHOAN-----------------
-- NHAN VIEN 
INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('NGUYENDANGKHOA','12345',N'KHOA NGUYỄN','QUAN LY')
INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('NGUYENTRUNGKIEN','12345',N'KIÊN NGUYỄN','QUAN LY')

INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN,AVATAR) 
   VALUES('NGUYENPHUCHOAILINH','12345',N'KHÔNG NHỚ TÊN','NHAN VIEN MUA BAN',N'Img/TaiKhoan/KhongNhoTen.png')
INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('CHUANHTOAN','12345',N'TOÀN SIDA','NHAN VIEN MUA BAN')

INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('NGUYENTHANHLOC','1245',N'CHÚ TƯ','NHAN VIEN SUA CHUA')
INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('HUYNHTUANANH','12345',N'ANH QQ','NHAN VIEN SUA CHUA')

-- KHACH HANG
INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG1','12345',N'KHACH H 1','KHACH')
INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG2','12345',N'KHACH H 2','KHACH')
INSERT INTO TAIKHOAN(USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG3','12345',N'KHACH H 3','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG4','12345',N'KHACH H 4','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG5','12345',N'KHACH H 5','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG6','12345',N'KHACH H 6','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG7','12345',N'KHACH H 7','KHACH') 
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG8','12345',N'KHACH H 8','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG9','12345',N'KHACH H 9','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG10','12345',N'KHACH H 10','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG11','12345',N'KHACH H 11','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG12','12345',N'KHACH H 12','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG13','12345',N'KHACH H 13','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG14','12345',N'KHACH H 14','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG15','12345',N'KHACH H 15','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG16','12345',N'KHACH H 16','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG17','12345',N'KHACH H 17','KHACH')
  INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG18','12345',N'KHACH H 18','KHACH')
INSERT INTO TAIKHOAN( USERNAME,PASS,DISLAY_NAME,LOAI_TAI_KHOAN) 
   VALUES('KHACHHANG19','12345',N'KHACH H 19','KHACH')              
-------------------------------NHOM QUYEN CO BAN-----------------------
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',1)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',2)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',3)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',4)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',5)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',6)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',7)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',8)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',9)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',10)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',11)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',12)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',13)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',14)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',15)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',16)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',17)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('ADMIN',18)

INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN MUA BAN',13)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN MUA BAN',14)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN MUA BAN',15)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN MUA BAN',16)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN MUA BAN',17)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN MUA BAN',18)

INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN SUA CHUA',9)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN SUA CHUA',14)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN SUA CHUA',15)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN SUA CHUA',16)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN SUA CHUA',17)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('NHAN VIEN SUA CHUA',18)

INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',3)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',4)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',5)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',6)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',14)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',15)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',16)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',17)
INSERT INTO NHOMQUYEN_COBAN(LOAI_TK,MAQUYEN_CON) VALUES('KHACH',18)

-----------------------------NHAN VIEN----------------------------
insert into NHANVIEN(TENNV,CMND,QUEQUAN,NAMSINH,DIACHITHUONGTRU,SDT,LUONG,CHUCVU,MATK,ANHCHANDUNG)
VALUES(N'Nguyễn Đăng Khoa', '3445215',N'Tiền Giang','1999/02/21',N'Quận Thủ đức, TPHCM','0334332153',20000,N'QUAN LY',1,'Img/NhanVien/Default.jpg') 
insert into NHANVIEN(TENNV,CMND,QUEQUAN,NAMSINH,DIACHITHUONGTRU,SDT,LUONG,CHUCVU,MATK,ANHCHANDUNG)
VALUES(N'Nguyễn Trung Kiên', '3445214',N'TPHCM','1999/02/1',N'Quận Thủ đức, TPHCM','0334332143',20000,N'QUAN LY',2,'Img/NhanVien/Default.jpg') 
insert into NHANVIEN(TENNV,CMND,QUEQUAN,NAMSINH,DIACHITHUONGTRU,SDT,LUONG,CHUCVU,MATK,ANHCHANDUNG)
VALUES(N'Nguyễn Phúc Hoài Linh', '3244214',N'Đồng Tháp','1999/03/11',N'Quận Thủ đức, TPHCM','0334012143',10000,N'NHAN VIEN MUA BAN',3,'Img/NhanVien/Default.jpg') 
insert into NHANVIEN(TENNV,CMND,QUEQUAN,NAMSINH,DIACHITHUONGTRU,SDT,LUONG,CHUCVU,MATK,ANHCHANDUNG)
VALUES(N'Chu Anh Toàn', '3104215',N'TPHCM','1999/05/10',N'Quận Thủ đức, TPHCM','0334012143',10000,N'NHAN VIEN MUA BAN',3,'Img/NhanVien/ChuAnhToan.jpg') 
insert into NHANVIEN(TENNV,CMND,QUEQUAN,NAMSINH,DIACHITHUONGTRU,SDT,LUONG,CHUCVU,MATK,ANHCHANDUNG)
VALUES(N'Nguyễn Thanh Lộc', '3244002',N'Gia Lai','1999/03/11',N'Quận Thủ đức, TPHCM','0334012143',15000,N'NHAN VIEN SUA CHUA',4,'Img/NhanVien/Default.jpg') 
insert into NHANVIEN(TENNV,CMND,QUEQUAN,NAMSINH,DIACHITHUONGTRU,SDT,LUONG,CHUCVU,MATK,ANHCHANDUNG)
VALUES(N'Huỳnh Tuấn Anh', '3244002',N'Đồng Nai','1999/03/11',N'Quận Thủ đức, TPHCM','0334012143',15000,N'NHAN VIEN SUA CHUA',5,'Img/NhanVien/HuynhTuanAnh.jpg') 

-----------------------------KHACH HANG---------------------------

INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Trần Quỳnh Thảo Nhi','033122312',N'Phường 1, Q.Bình Thạnh, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Văn Lâm','033122002',N'Phường 1, Q.Bình Thạnh, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Lê Nhân Minh','033110712',N'Phường 3, Quận 3, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Cao Minh','030187312',N'Phường 1, Quận 3, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Lê Nhứt Chinh','033091412',N'Phường 2, Quận 4, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Văn Chiêu','030929112',N'Phường 5, Q.Bình Thạnh, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Thị Nở','033002312',N'Phường 4, Quận 4, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Trần Chí Phèo','033100312',N'Phường 10, Quận 2, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Lê Tùng Dương','033214322',N'Phường 9, Quận 1, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Huỳnh Thảo Vi','033001212',N'Phường 5, Quận 1, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Lê Thiên Khôi','035109312',N'Phường 2, Quận 4, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Quốc Tuấn','035091312',N'Phường 9, Q.Bình Chánh, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Nhi Quỳnh','035002312',N'Phường 8, Q.Bình Chánh, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Thị Lan','033001212',N'Phường 7, Q.Tân Phú, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Nguyễn Thị Yến Lan','033302912',N'Phường 4, Q.Bình Thạnh, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Trần Anh Tuấn','033122312',N'Phường 2, Q.Tân Phú, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Lê Cao Nhi','033091516',N'Phường 5, Quận 1, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Cao Văn Cường','033127085',N'Phường 6, Quận 4, TPHCM')
INSERT INTO KHACHHANG(TENKH,SDT,DIACHI) VALUES(N'Trần Nhi Thương','033122090',N'Phường 7, Quận 1, TPHCM')

------ HANG SAN XUAT 
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('SAMSUNG',N'Hàn Quốc')  -- 1
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('Xiaomi',N'Trung Quốc') -- 2
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('OPPO',N'Trung Quốc')   -- 3
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('SONY',N'Nhật Bản')     -- 4
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('NOKIA',N'Phần Lan')    -- 5
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('VIVO',N'Trung Quốc')   -- 6
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('Huawei',N'Trung Quốc') -- 7
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('None',N'Trung Quốc') -- 8
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('Xmobile',N'Trung Quốc') -- 9
INSERT INTO HANGSX(TENHANG,QUOCGIA) VALUES('LG',N'Hàn Quốc') -- 10
------ SANPHAM 
--dien thoai
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Samsung Galaxy A10',3100,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.2inch;Camera sau:13 MP;Camera trước:5 MP;Hệ điều hành:Android 9.0;RAM:2 GB;Bộ nhớ trong:32 GB;Trọng lượng:168 g;Dung lượng pin:3400 mAh;Thời điểm ra mắt:04/2019',
'Img/SanPham/DienThoai/SAMSUNG/samsung-galaxy-a10.png',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Samsung Galaxy Note 10',26990,'DIEN THOAI',
N'Công nghệ màn hình:Dynamic AMOLED;Màn hình rộng:6.8 inch;Camera sau:Chính 12 MP & Phụ 12 MP;Camera trước:10 MP;Hệ điều hành:Android 9.0;RAM:12 GB;Bộ nhớ trong:256 GB;Trọng lượng:196 g;Dung lượng pin:4300 mAh;Thời điểm ra mắt:08/2019',
'Img/SanPham/DienThoai/SAMSUNG/samsung-galaxy-note-10.png',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Samsung Galaxy S10+',22990,'DIEN THOAI',
N'Công nghệ màn hình:Dynamic AMOLED;Màn hình rộng:6.4 inch;Camera sau:Chính 12 MP & Phụ 12 MP;Camera trước:Chính 10 MP & Phụ 8 MP;Hệ điều hành:Android 9.0;RAM:8 GB;Bộ nhớ trong:128 GB;Trọng lượng:175 g;Dung lượng pin:4100 mAh;Thời điểm ra mắt:02/2019',
'Img/SanPham/DienThoai/SAMSUNG/samsung-galaxy-s10.png',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Samsung Galaxy J4+',2590,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.0 inch;Camera sau:13 MP;Camera trước:5 MP;Hệ điều hành:Android 8.1;RAM:2 GB;Bộ nhớ trong:16 GB;Trọng lượng:176 g;Dung lượng pin:3300 mAh;Thời điểm ra mắt:10/2018',
'Img/SanPham/DienThoai/SAMSUNG/samsung-galaxy-j4.png',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Samsung Galaxy A20',4190,'DIEN THOAI',
N'Công nghệ màn hình:Super AMOLED;Màn hình rộng:6.4 inch;Camera sau:Chính 13 MP & Phụ 5 MP;Camera trước:8 MP;Hệ điều hành:Android 9.0;RAM:3 GB;Bộ nhớ trong:32 GB;Trọng lượng:169 g;Dung lượng pin:4000 mAh;Thời điểm ra mắt:04/2019',
'Img/SanPham/DienThoai/SAMSUNG/samsung-galaxy-a20.png',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Samsung Galaxy A7',7990,'DIEN THOAI',
N'Công nghệ màn hình:Super AMOLED;Màn hình rộng:6.0 inch;Camera sau:Chính 24 MP & Phụ 8 MP;Camera trước:24 MP;Hệ điều hành:Android 8.0;RAM:6 GB;Bộ nhớ trong:128 GB;Trọng lượng:169 g;Dung lượng pin:3300 mAh;Thời điểm ra mắt:10/2018',
'Img/SanPham/DienThoai/SAMSUNG/samsung-galaxy-a7.png',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Xiaomi Redmi 8A',2590,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.22 inch;Camera sau:12 MP;Camera trước:8 MP;Hệ điều hành:Android 9.0;RAM:2 GB;Bộ nhớ trong:32 GB;Trọng lượng:188 g;Dung lượng pin:5000 mAh;Thời điểm ra mắt:10/2019',
'Img/SanPham/DienThoai/Xiaomi/xiaomi-redmi-8a.png',2)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Xiaomi Mi 9T',7990,'DIEN THOAI',
N'Công nghệ màn hình:AMOLED;Màn hình rộng:6.39 inch;Camera sau:Chính 48 MP & Phụ 13 MP;Camera trước:20 MP;Hệ điều hành:Android 9.0;RAM:6 GB;Bộ nhớ trong:64 GB;Trọng lượng:191 g;Dung lượng pin:4000 mAh;Thời điểm ra mắt:07/2019',
'Img/SanPham/DienThoai/Xiaomi/xiaomi-mi-9t.png',2)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Xiaomi Redmi Note 7',4490,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.3 inch;Camera sau:Chính 48 MP & Phụ 5 MP;Camera trước:13 MP;Hệ điều hành:Android 9.0;RAM:4 GB;Bộ nhớ trong:64 GB;Trọng lượng:186 g;Dung lượng pin:4000 mAh;Thời điểm ra mắt:03/2019',
'Img/SanPham/DienThoai/Xiaomi/xiaomi-redmi-note-7.png',2)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'OPPO A5s',3690,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.2 inch;Camera sau:Chính 13 MP & Phụ 2 MP;Camera trước:8 MP;Hệ điều hành:Android 8.1;RAM:3 GB;Bộ nhớ trong:32 GB;Trọng lượng:170 g;Dung lượng pin:4230 mAh;Thời điểm ra mắt:05/2019',
'Img/SanPham/DienThoai/OPPO/oppo-a5s.png',3)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'OPPO A7',4590,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.2 inch;Camera sau:Chính 13 MP & Phụ 2 MP;Camera trước:16 MP;Hệ điều hành:ColorOS 5.2;RAM:4 GB;Bộ nhớ trong:64 GB;Trọng lượng:158 g;Dung lượng pin:4230 mAh;Thời điểm ra mắt:11/2018',
'Img/SanPham/DienThoai/OPPO/oppo-a7.png',3)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Nokia 3.2 ',2490,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.2 inch;Camera sau:Chính 13 MP;Camera trước:5 MP;Hệ điều hành:Android 9.0;RAM:2 GB;Bộ nhớ trong:16 GB;Trọng lượng:178 g;Dung lượng pin:4000 mAh;Thời điểm ra mắt:05/2018',
'Img/SanPham/DienThoai/NOKIA/nokia-32.png',5)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Nokia 6.1',3790,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:5.8 inch;Camera sau:Chính 16 MP & Phụ 5 MP;Camera trước:16 MP;Hệ điều hành:Android 8.0;RAM:4 GB;Bộ nhớ trong:64 GB;Trọng lượng:153 g;Dung lượng pin:3000 mAh;Thời điểm ra mắt:08/2018',
'Img/SanPham/DienThoai/NOKIA/nokia-32.png',5)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Vivo Y11',2990,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.35 inch;Camera sau:Chính 13 MP & Phụ 2 MP;Camera trước:8 MP;Hệ điều hành:Android 9.0;RAM:3 GB;Bộ nhớ trong:32 GB;Trọng lượng:190 g;Dung lượng pin:5000 mAh;Thời điểm ra mắt:10/2018',
'Img/SanPham/DienThoai/VIVO/vivo-y11.png',6)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Vivo Y19',4990,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.53 inch;Camera sau:Chính 16 MP & Phụ 8 MP;Camera trước:16 MP;Hệ điều hành:Android 9.0;RAM:6 GB;Bộ nhớ trong:128 GB;Trọng lượng:193 g;Dung lượng pin:5000 mAh;Thời điểm ra mắt:11/2019',
'Img/SanPham/DienThoai/VIVO/vivo-y19.png',6)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Huawei Y9',4990,'DIEN THOAI',
N'Công nghệ màn hình:LTPS LCD;Màn hình rộng:6.5 inch;Camera sau:Chính 13 MP & Phụ 2 MP;Camera trước:Chính 16 MP & Phụ 2 MP;Hệ điều hành:Android 8.1;RAM:4 GB;Bộ nhớ trong:64 GB;Trọng lượng:173 g;Dung lượng pin:4000 mAh;Thời điểm ra mắt:10/2018',
'Img/SanPham/DienThoai/Huawei/huawei-y9.png',7)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Huawei P30 Lite',6020,'DIEN THOAI',
N'Công nghệ màn hình:IPS LCD;Màn hình rộng:6.15 inch;Camera sau:Chính 24 MP & Phụ 8 MP;Camera trước:32 MP;Hệ điều hành:Android 9.0;RAM:4 GB;Bộ nhớ trong:6 GB;Trọng lượng:128 g;Dung lượng pin:3340 mAh;Thời điểm ra mắt:3/2019',
'Img/SanPham/DienThoai/Huawei/huawei-p30-lite.png',7)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Huawei Nova 3i',5990,'DIEN THOAI',
N'Công nghệ màn hình:LTPS LCD;Màn hình rộng:6.3 inch;Camera sau:Chính 16 MP & Phụ 2 MP;Camera trước:Chính 24 MP & Phụ 2 MP;Hệ điều hành:Android 8.1;RAM:4 GB;Bộ nhớ trong:4 GB;Trọng lượng:169 g;Dung lượng pin:3340 mAh;Thời điểm ra mắt:7/2018',
'Img/SanPham/DienThoai/Huawei/huawei-y9.png',7)


--- linh kien
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Pin sạc dự phòng 5.000 mAh eSaver Safari 2S',200,'LINH KIEN',
N'Hiệu suất sạc:65%;Dung lượng pin:5.000 mAh;Nguồn vào:5V - 2A;Nguồn ra:5V - 1A, 5V - 2.1A;Tiện ích:Đèn LED báo hiệu;Trọng lượng:200g',
'Img/SanPham/LinhKien/SacDuPhong/pin-sac-du-phong-5000mah-esaver-safari.jpg',8)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Pin sạc dự phòng 5.000 mAh eSaver LA A32',120,'LINH KIEN',
N'Hiệu suất sạc:65%;Dung lượng pin:5.000 mAh;Nguồn vào:5V - 2A;Nguồn ra:5V - 1A, 5V - 2.1A;Tiện ích:Đèn LED báo hiệu;Trọng lượng:138.5g',
'Img/SanPham/LinhKien/SacDuPhong/pin-sac-du-phong-5000mah-esaver-la-a32.jpg',8)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Pin sạc dự phòng 7.500 mAh AVA LA CT23',250,'LINH KIEN',
N'Hiệu suất sạc:65%;Dung lượng pin:5.000 mAh;Nguồn vào:5V - 2.1A;Nguồn ra:5V - 2A;Tiện ích:Đèn LED báo hiệu;Trọng lượng:184g',
'Img/SanPham/LinhKien/SacDuPhong/pin-sac-du-phong-7500mah-ava.jpg',8)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Pin sạc dự phòng 5.000 mAh eSaver Safari 2',120,'LINH KIEN',
N'Hiệu suất sạc:65%;Dung lượng pin:5.000 mAh;Nguồn vào:5V - 2A;Nguồn ra:5V - 1A, 5V - 2.1A;Tiện ích:Đèn LED báo hiệu;Trọng lượng:200g',
'Img/SanPham/LinhKien/SacDuPhong/pin-sac-du-phong-5000mah-esaver-safari-2.jpg',8)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Pin sạc dự phòng 7.500 mAh eSaver LA A33',260,'LINH KIEN',
N'Hiệu suất sạc:65%;Dung lượng pin:7.500 mAh;Nguồn vào:5V - 2A;Nguồn ra:5V - 1A, 5V - 2.1A;Tiện ích:Đèn LED báo hiệu;Trọng lượng:200g',
'Img/SanPham/LinhKien/SacDuPhong/pin-sac-du-phong-7500mah-esaver-la-a33.jpg',8)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Pin sạc dự phòng Polymer 5.000 mAh Sony CP-V5B',690,'LINH KIEN',
N'Hiệu suất sạc:57%;Dung lượng pin:5.000 mAh;Nguồn vào:5V - 1.5A;Nguồn ra:5V - 1.5A;Tiện ích:Đèn LED báo hiệu;Trọng lượng:133g',
'Img/SanPham/LinhKien/SacDuPhong/pin-sac-du-phong-7500mah-esaver-la-a33.jpg',4)

INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Cáp Xmobile Micro USB 25 cm',20,'LINH KIEN',
N'Chức năng:Truyền dữ liệu,Sạc',
'Img/SanPham/LinhKien/DayCap/cap-x-mobile-micro-usb-25cm.jpg',9)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Cáp Type-C 1 m Sony CP-AC100',190,'LINH KIEN',
N'Chức năng:Truyền dữ liệu,Sạc;Đầu ra:Type C',
'Img/SanPham/LinhKien/DayCap/cap-type-c-1m-sony-cp-ac100-12.jpg',4)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Cáp Type-C 1.5 m Sony CP-AC150',220,'LINH KIEN',
N'Chức năng:Truyền dữ liệu,Sạc;Đầu ra:Type C',
'Img/SanPham/LinhKien/DayCap/cap-type-c-15m-sony-cp-ac150-ava.jpg',4)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Bộ Adapter Sony CP-AD2A',390,'LINH KIEN',
N'Chức năng:Sạc',
'Img/SanPham/LinhKien/DayCap/bo-adapter-sac-21a-kem-cap-type-c-15m-sony-cp-ad2a.jpg',4)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Bộ Adapter Sony CP-AD2M',390,'LINH KIEN',
N'Chức năng:Sạc',
'Img/SanPham/LinhKien/DayCap/bo-adapter-sac-2-cong-3a-kem-cap-micro-50cm.jpg',4)

INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Tai nghe nhét trong Samsung EG920B',280,'LINH KIEN',
N'Jack cắm:3.5mm;Độ dài dây:1.2 m;Kết nối cùng lúc:1 thiết bị;Sản xuất tại:Trung Quốc',
'Img/SanPham/LinhKien/TaiNghe/tai-nghe-nhet-trong-samsung-eg920b.jpg',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Tai nghe nhét trong Samsung IG935B',300,'LINH KIEN',
N'Jack cắm:3.5mm;Độ dài dây:1.2 m;Kết nối cùng lúc:1 thiết bị;Trọng lượng:13.2 g;Sản xuất tại:Việt Nam',
'Img/SanPham/LinhKien/TaiNghe/tai-nghe-nhet-trong-samsung-ig935.jpg',1)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Tai nghe Bluetooth LG HBS-510 ',899,'LINH KIEN',
N'Jack cắm:3.5mm;Độ dài dây:1.2 m;Kết nối cùng lúc:1 thiết bị;Trọng lượng:13.2 g;Sản xuất tại:Việt Nam',
'Img/SanPham/LinhKien/TaiNghe/tai-nghe-bluetooth-lg-hbs-510-den-1.jpg',10)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Tai nghe Bluetooth LG HBS-835',1899,'LINH KIEN',
N'Cổng sạc:Micro USB;Độ dài dây:Dây ngắn;Công nghệ âm thanh:Quad Layer;Thời gian sử dụng:13 giờ;Thời gian sạc đầy:2 giờ;Kết nối cùng lúc:1 thiết bị;Khoảng cách kết nối:10 m;Trọng lượng:40.7 g',
'Img/SanPham/LinhKien/TaiNghe/tai-nghe-bluetooth-lg-hbs-835-den.jpg',10)

INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Thẻ nhớ MicroSD 128 GB Class 10',1099,'LINH KIEN',
N'Dung lượng:128 GB;Chuẩn tốc độ:Class 10;Tốc độ đọc dữ liệu:45 MB/s;Tốc độ ghi dữ liệu:10 MB/s',
'Img/SanPham/LinhKien/TheNho/the-nho-microsd-128gb-class-10-uhs1.jpg',10)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Thẻ nhớ MicroSD 16 GB Class 10',299,'LINH KIEN',
N'Dung lượng:16 GB;Tốc độ đọc dữ liệu:30 MB/s;Tốc độ ghi dữ liệu:10 MB/s',
'Img/SanPham/LinhKien/TheNho/the-nho-microsd-16gb-class-10-9.jpg',10)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Thẻ nhớ SD 8 GB Transcend Class 10',150,'LINH KIEN',
N'Dung lượng:8 GB;Chuẩn tốc độ:Class 10;Tốc độ đọc dữ liệu:20 MB/s;Tốc độ ghi dữ liệu:17 MB/s',
'Img/SanPham/LinhKien/TheNho/the-nho-sdxc-sdhc-class-10-transcend.jpg',10)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Thẻ nhớ CF 128 GB Transcend 800x',3000,'LINH KIEN',
N'Dung lượng:128 GB;Chuẩn tốc độ:Class 2;Tốc độ đọc dữ liệu:120 MB/s;Tốc độ ghi dữ liệu:60 MB/s',
'Img/SanPham/LinhKien/TheNho/the-nho-cf-800x-transcend-128gb.jpg',10)
INSERT INTO SANPHAM(TENSP,GIA,LOAI,CHITIET,DUONGDAN_HINHANH,MAHSX) VALUES(N'Thẻ nhớ MicroSD 64 GB Class 10',550,'LINH KIEN',
N'Dung lượng:64 GB;Tốc độ đọc dữ liệu:45 MB/s;Tốc độ ghi dữ liệu:10 MB/s',
'Img/SanPham/LinhKien/TheNho/the-nho-microsd-64gb-class-10u1.jpg',10)

--------------DANH GIA
INSERT INTO DANHGIA(MASP,TOTAL_SCORE,TOW_STAR,THREE_STAR,FIVE_STAR) VALUES (1,3,1,1,1)
INSERT INTO DANHGIA(MASP) VALUES (2)
INSERT INTO DANHGIA(MASP) VALUES (3)
INSERT INTO DANHGIA(MASP) VALUES (4)
INSERT INTO DANHGIA(MASP) VALUES (5)
INSERT INTO DANHGIA(MASP) VALUES (6)
INSERT INTO DANHGIA(MASP) VALUES (7)
INSERT INTO DANHGIA(MASP) VALUES (8)
INSERT INTO DANHGIA(MASP) VALUES (9)
INSERT INTO DANHGIA(MASP) VALUES (10)
INSERT INTO DANHGIA(MASP) VALUES (11)
INSERT INTO DANHGIA(MASP) VALUES (12)
INSERT INTO DANHGIA(MASP) VALUES (13)
INSERT INTO DANHGIA(MASP) VALUES (14)
INSERT INTO DANHGIA(MASP) VALUES (15)
INSERT INTO DANHGIA(MASP) VALUES (16)
INSERT INTO DANHGIA(MASP) VALUES (17)
INSERT INTO DANHGIA(MASP) VALUES (18)
INSERT INTO DANHGIA(MASP) VALUES (19)
INSERT INTO DANHGIA(MASP) VALUES (20)
INSERT INTO DANHGIA(MASP) VALUES (21)
INSERT INTO DANHGIA(MASP) VALUES (22)
INSERT INTO DANHGIA(MASP) VALUES (23)
INSERT INTO DANHGIA(MASP) VALUES (24)
INSERT INTO DANHGIA(MASP) VALUES (25)
INSERT INTO DANHGIA(MASP) VALUES (26)
INSERT INTO DANHGIA(MASP) VALUES (27)
INSERT INTO DANHGIA(MASP) VALUES (28)
INSERT INTO DANHGIA(MASP) VALUES (29)
INSERT INTO DANHGIA(MASP) VALUES (30)
INSERT INTO DANHGIA(MASP) VALUES (31)
INSERT INTO DANHGIA(MASP) VALUES (32)
INSERT INTO DANHGIA(MASP) VALUES (33)
INSERT INTO DANHGIA(MASP) VALUES (34)
INSERT INTO DANHGIA(MASP) VALUES (35)
INSERT INTO DANHGIA(MASP) VALUES (36)
INSERT INTO DANHGIA(MASP) VALUES (37)
INSERT INTO DANHGIA(MASP) VALUES (38)

------------TAI KHOAN KHACH 
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(1,7,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(2,8,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(3,9,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(4,10,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(5,11,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(6,12,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(7,13,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(8,14,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(9,15,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(10,16,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(11,17,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(12,18,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(13,19,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(14,20,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(15,21,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(16,22,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(17,23,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(18,24,'VANG LAI')
INSERT INTO TAIKHOAN_KHACH(MAKH,MATAIKHOAN,LOAI_KHACH) VALUES(19,25,'VANG LAI')


-----------------BINH LUAN
INSERT INTO NHANXET_SP (MASP,MATAIKHOAN,TITILE,NOIDUNG,LIKE_,DISLIKE,SCORE) VALUES (1,1,N'Sản phẩm như hạch ấy!',N'Đề nghị tụt quần bắn tờ rym thằng chủ shop',1,4,3) 
INSERT INTO NHANXET_SP (MASP,MATAIKHOAN,TITILE,NOIDUNG,LIKE_,DISLIKE,SCORE) VALUES(1,2,N'Sản Phâm Rất Ngon',N'Sản phẩm này thật lợi hại, Nó đã giúp tôi ngủ được buổi tối và thức vào buổi sáng,ăn cơm có thể hết đói , uống nước có thể hết khát. Thật lợi hại.' ,6,1,5)
INSERT INTO NHANXET_SP (MASP,MATAIKHOAN,TITILE,NOIDUNG,LIKE_,DISLIKE,SCORE) VALUES(1,3,N'Hừm...',N'Điện thoại này thật là tà đạo. Nó đã khiến tôi trở nên lú lẩn. Khiến tôi đi cấu kết với thương gia buôn bán vũ khí, cưỡng dâm một con heo, đầy bà già xuống biển. Giờ nghĩ lại thì thấy mình thật có lỗi quá đi. 
Chiếc điện thoại này quả là tà đạo, tà đạo quá đi mà' ,20,1,2)


-----------------THEM SAN PHAM VAO GIO HANG

INSERT INTO GIOHANG(MATAIKHOAN,MA_SANPHAM,SOLUONG,DAMUA) VALUES(3,1,2,0)
INSERT INTO GIOHANG(MATAIKHOAN,MA_SANPHAM,SOLUONG,DAMUA) VALUES(3,9,1,0)
INSERT INTO GIOHANG(MATAIKHOAN,MA_SANPHAM,SOLUONG,DAMUA) VALUES(3,5,1,0)

--select * from TAIKHOAN tk, NHANXET_SP nx where tk.MATAIKHOAN =  nx.MATAIKHOAN and MASP = 1


